general.import = ["~/.config/alacritty/colors/catpuccino-mocca.toml"]

general.live_config_reload = true


window.title = "Gonz's terminal"

[window.dimensions]
columns = 80
lines = 26


[font]
size = 12.0

[font.bold]
family = "0xProto Nerd Font"

[font.bold_italic]
family = "0xProto Nerd Font"

[font.italic]
family = "0xProto Nerd Font"

[font.normal]
family = "0xProto Nerd Font"

[window.padding]
x = 10
y = 5
